# .bashrc

#
# --- Global ---
#

[ -f /etc/bashrc ] && . /etc/bashrc

#
# --- User ---
#

#alias rm='rm -i'
#alias cp='cp -i'
#alias mv='mv -i'

alias ls='ls -AFlNh --group-directories-first --color=auto'

#alias sed='sed -En'

#
# GPG
#

alias gpga='gpgconf -K gpg-agent && gpgconf --launch gpg-agent'
alias gls='gpg-connect-agent -q "keyinfo --list" /bye && gpg --list-keys --with-fingerprint --with-keygrip'
alias glsp='gpg-connect-agent -q "keyinfo --list" /bye && gpg --list-secret-keys --with-fingerprint --with-keygrip'
alias gpe='gpg --expert --edit-key'

#
# Git
#

alias gs='git status --show-stash'
alias gsi='gs --ignored'
alias gl='git log --abbrev-commit --graph --shortstat'
alias glo='git log --abbrev-commit --graph --oneline'
alias gd='git diff'
alias gdd='gd --compact-summary'
alias gb='git branch'

#alias gic='gc --allow-empty -m "Initial commit"'

alias ga.='git add .'
alias gc='git commit'
alias gc.='ga. && gc -m'
alias gca.='ga. && gc --amend'
alias gr='git rebase --committer-date-is-author-date'
alias grc='git rebase --continue'
alias grc.='ga. && grc'

alias gp="git push"
alias gpf='gp -f --force-with-lease'

alias gsw='git switch'
alias gsw-='gsw -'
alias gsw-m='gsw main'
alias gsw-d='gsw develop'
alias gsw-l='gsw local-changes'

#
# Git Flow
#

alias gf='git flow'
alias gff='gf feature'
alias gfb='gf bugfix'
alias gfh='gf hotfix'
alias gfr='gf release'
alias gfs='gf support'
alias gfv='gf version'

alias gf-lf='gff list'
alias gf-sf='gff start'
alias gf-ff='gff finish'
alias gf-cf='gff checkout'
alias gf-rf='gff rebase'

alias gf-lb='gfb list'
alias gf-sb='gfb start'
alias gf-fb='gfb finish'
alias gf-cb='gfb checkout'
alias gf-rb='gfb rebase'

alias gf-lh='gfh list'
alias gf-sh='gfh start'
alias gf-fh='gfh finish'

alias gf-lr='gfr list'
alias gf-sr='gfr start'
alias gf-fr='gfr finish'

alias gf-ls='gfs list'
alias gf-ss='gfs start'

#
# .Net
#

alias dnclean='dotnet clean -v minimal && dotnet restore && dotnet build --no-restore --no-incremental'
alias gitversion='~/.dotnet/tools/dotnet-gitversion'
alias gv='gitversion'
#alias nbgv='~/.dotnet/tools/nbgv'

#
# Other
#

alias diff='diff --report-identical-files --side-by-side --ignore-all-space --ignore-blank-lines --strip-trailing-cr --color=auto'
#alias k3='~/AppData/Local/KDiff3/bin/kdiff3.exe'
